### ISSUE TITLE
Some clarity issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [PitchapaSaelim/ku-polls#1]
> 4.&nbsp;This web application has automatic way to set a start and end date.

"start and end date" for what? If it's for each poll you should include that.

> 2.&nbsp;User is allowed to view a previous submission.
> 3.&nbsp;User is allowed to edit a previous submission.

> 6.&nbsp;This web application provides the ability to submit a choice on poll items and view or modify one’s choice any time during the polling period.

> 9.&nbsp;This web application does not allowed web visitors to vote or modify an existing vote after the closing date.

How is a "submission" and an "existing vote" different? If not, these requirements seem to be in some conflict. Some clarification would be good. If so, how? Some explanation would be nice.

> 10.&nbsp;The poll/survey question and results in this web application can still be viewed after the closing date.

As Mr James has posted in the classroom this morning, use "poll" instead of "survey" for now.

> 8.&nbsp;This web application does not allowed web visitors to view before the opening date

"to view" what? "the opening date" of what? each poll? If so, include that.

The word "web application" also isn't really needed (though I'm not sure if it's bad or not; it just sounds strange and unnecessarily verbose to me—but don't get me wrong; necessary verbosity for clarity isn't bad). If you wish to write requirements without it, you could simply say things like "Web visitors are not allowed to view the poll before the opening date."

**Comment by PitchapaSaelim** [comment]
I fixed it. Thank you.
